
# dice Game
echo "enter the Sum and try your luck."
# taking input as a sum
read sum

function random_generate {
# generating random number using RANDOM
number=$RANDOM

# generating that random between 0 to 5
div=`expr $number % 6`

# making it between 1 to 6
let div=div+1
echo $div
}
dice_sum=0
# running until break
while [[ true ]]
do 
# calling random_generate function
dice_value=$(random_generate)
# incrementing dice sum value by adding the random generated value.
let dice_sum=dice_sum+dice_value
echo "$dice_sum this is your sum till now."
# if anytime sum is equal to the sum generated by adding random 
generated value from dice you will win
if [[ $dice_sum -eq $sum ]]
then 
echo "Congratulations you won the dice game"
break
elif [[ $dice_sum -gt $sum ]]
then
echo "Sorry You lost"
break
fi
done

